export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_RECIPES_INIT = 'GET_RECIPES_INIT';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAIL = 'GET_RECIPES_FAIL';

export const GET_RECIPE_INIT = 'GET_RECIPE_INIT';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
export const GET_RECIPE_FAIL = 'GET_RECIPE_FAIL';

export const GET_MY_RECIPE_INIT = 'GET_MY_RECIPE_INIT';
export const GET_MY_RECIPE_SUCCESS = 'GET_MY_RECIPE_SUCCESS';
export const GET_MY_RECIPE_FAIL = 'GET_MY_RECIPE_FAIL';

export const GET_MY_RECIPE_BY_ID_INIT = 'GET_MY_RECIPE_BY_ID_INIT';
export const GET_MY_RECIPE_BY_ID_SUCCESS = 'GET_MY_RECIPE_BY_ID_SUCCESS';
export const GET_MY_RECIPE_BY_ID_FAIL = 'GET_MY_RECIPE_BY_ID_FAIL';

export const GET_RECIPE_BY_ID_INIT = 'GET_RECIPE_BY_ID_INIT';
export const GET_RECIPE_BY_ID_SUCCESS = 'GET_RECIPE_BY_ID_SUCCESS';
export const GET_RECIPE_BY_ID_FAIL = 'GET_RECIPE_BY_ID_FAIL';
