export const GET_ERRORS = 'GET_ERRORS';

export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const GET_RECIPES_BY_CATEGORY = 'GET_RECIPES_BY_CATEGORY';
export const GET_RECIPE_BY_CATEGORY_ID = 'GET_RECIPE_BY_CATEGORY_ID';
export const GET_RECIPES_BY_COURSE = 'GET_RECIPES_BY_COURSE';
export const GET_RECIPE_BY_COURSE_ID = 'GET_RECIPE_BY_COURSE_ID';

export const GET_MY_RECIPES = 'GET_MY_RECIPES';
export const POST_MY_RECIPE_ID = 'POST_MY_RECIPE_ID';
