export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_CATEGORY = 'GET_RECIPE_CATEGORY';
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
