export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_RECIPES_INIT = 'GET_RECIPES_INIT';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR';

export const GET_RECIPE_INIT = 'GET_RECIPE_INIT';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
export const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR';

export const GET_MY_RECIPE_INIT = 'GET_MY_RECIPE_INIT';
export const GET_MY_RECIPE_SUCCESS = 'GET_MY_RECIPE_SUCCESS';
export const GET_MY_RECIPE_ERROR = 'GET_MY_RECIPE_ERROR';

export const GET_MY_RECIPE_BY_ID_INIT = 'GET_MY_RECIPE_BY_ID_INIT';
export const GET_MY_RECIPE_BY_ID_SUCCESS = 'GET_MY_RECIPE_BY_ID_SUCCESS';
export const GET_MY_RECIPE_BY_ID_ERROR = 'GET_MY_RECIPE_BY_ID_ERROR';

export const GET_RECIPE_BY_ID_INIT = 'GET_RECIPE_BY_ID_INIT';
export const GET_RECIPE_BY_ID_SUCCESS = 'GET_RECIPE_BY_ID_SUCCESS';
export const GET_RECIPE_BY_ID_ERROR = 'GET_RECIPE_BY_ID_ERROR';

export const POST_FILE_UPLOAD_INIT = 'POST_FILE_UPLOAD_INIT';
export const POST_FILE_UPLOAD_SUCCESS = 'POST_FILE_UPLOAD_SUCCESS';
export const POST_FILE_UPLOAD_ERROR = 'POST_FILE_UPLOAD_ERROR';
